### ISSUE TITLE
Inconsistency in Company Name field.

### ISSUE THREAD

**Issue by konarkmodi** [cliqz-oss/whotracks.me#112]
While looking at the `assets/trackerdb.sql`, in the table `trackers` lot of times the company names are with quotes like  `"company name"` and at times without quotes, is there a reason for it?

```select name from trackers limit 10;
name
"Google Analytics"
DoubleClick
Google
"Google APIs"
"Google Tag Manager"
Facebook
INFOnline
"Google AdServices"
"Google Syndication"
"Amazon Web Services"```

**Comment by ecnmst** [comment]
Hi @konarkmodi this should be fixed now. It was indeed just inconsistent naming - thanks for reporting. Source: https://github.com/cliqz-oss/whotracks.me/blob/master/whotracksme/data/assets/trackerdb.sql
