### ISSUE TITLE
A few more trackers for whotracksme

### ISSUE THREAD

**Issue by ameshkov** [cliqz-oss/whotracks.me#141]
Hi there! We've been accumulating some information on known trackers, and I guess it might be useful to you.

I've tried to make a proper pull request at first, but it's not that easy to convert what we have in your format:) Please take a look at the Doc, I've marked trackers that are missing or incomplete on whotracks.me.

https://docs.google.com/spreadsheets/d/19yJoE2UQ3eh1Gd26YMtWASBp7gh0xOBsNZr3xouggdI/edit?usp=sharing

**Comment by sammacbeth** [comment]
Thanks a lot for this - this is very helpful. We'll try and integrate it with our data and get back to you if there are any questions.

**Comment by ecnmst** [comment]
@ameshkov - thanks again, your contributions should now be part of the data.
