### ISSUE TITLE
RSS?

### ISSUE THREAD

**Issue by LeBaux** [cliqz-oss/whotracks.me#152]
I want to keep up with the blog but I don't want to add it on any social media, RSS would be great. Could you add RSS feed? Thank you.

**Comment by ecnmst** [comment]
Hi @LeBaux, happy to let you know whotracks.me now has an rss feed. You should have a link to it in the footer of the site.

**Comment by LeBaux** [comment]
I appreciate it, I know RSS is a bit ancient but it is also the last privacy friendly aggregation tool! Cheers 😃
