### ISSUE TITLE
IntentIQ and Datonics owned by AlmondNet

### ISSUE THREAD

**Issue by VictorLeP** [cliqz-oss/whotracks.me#191]
[IntentIQ](https://whotracks.me/trackers/intent_iq.html) and [Datonics](https://whotracks.me/trackers/datonics.html) appear to belong to the same group: [AlmondNet](https://www.almondnet.com/). Should this be reflected in the "Owned by" field?
(I'm not affiliated with these companies)

**Comment by sammacbeth** [comment]
Thanks for this, this checks out. Here are the sources:
 * "Our Parent Company – AlmondNet Group" https://www.intentiq.com/company
 * "Datonics (www.datonics.com), a subsidiary of AlmondNet..." https://www.datonics.com/about

I'll get this added to the next batch of database updates.
