### ISSUE TITLE
database update

### ISSUE THREAD

**Issue by ernests** [cliqz-oss/whotracks.me#199]
Hi!
I installed project from pip and after 

`data = DataSource()`

shows:

``
data available for months: ['2017-05', '2017-06', '2017-07', '2017-08', '2017-09', '2017-10', '2017-11', '2017-12', '2018-01', '2018-02', '2018-03', '2018-04']
``
Is there a way to download latest db or I just have to manually download db and then load the data?

**Comment by sammacbeth** [comment]
Hi. We stopped publishing to pip because the amount of data is too large. Your best bet would be to checkout the repo directly (don't forget to set up git-lfs to pull the data), then do a local pip install (`pip install /path/to/whotracks.me/`).

**Comment by ernests** [comment]
Thank you!
Great work.
