### ISSUE TITLE
Need clarity on licensing terms

### ISSUE THREAD

**Issue by lab4me** [cliqz-oss/whotracks.me#202]
Hi,

I have a query related to the licensing terms mentioned in this project. As licensing description is mentioned as below: 
"The content of this project itself is licensed under the Creative Commons Attribution 4.0 license, and the underlying source code used to generate and display that content is licensed under the MIT license."

Q1. Does it mean that all the data, including third party/tracker information present at https://github.com/cliqz-oss/whotracks.me/tree/master/whotracksme/data/assets, are covered under Creative Common Attribution 4.0 license?

Q2. Can I also use the data present here for some experiments in my personal project?

Regards,
Ethan

**Comment by sammacbeth** [comment]
Hi Ethan,

Yes, this sentence could be made a bit clearer:
 * The data (i.e. all csv files) is licensed under CC BY 4.0
 * The python code is licensed under MIT.

To answer your questsions:
 1. Yes
 2. Yes. As per the [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) conditions, you can do anything you want with this data, provided you state the attribution. i.e. link to whotracks.me or this github repo.

Hope that makes things clearer for you.
