### ISSUE TITLE
Downloading data / cloning a repository

### ISSUE THREAD

**Issue by karlolukic** [cliqz-oss/whotracks.me#215]
Hi guys,

I'm receiving a following error message after cloning this repo: "This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access."

I'm attaching the log file here: [20201102T112956.908151.log](https://github.com/cliqz-oss/whotracks.me/files/5474278/20201102T112956.908151.log)

Above error persist even after: `git lfs fetch`

Bascially all the files in the `whotracksme/data/assets/...` folders will not be converted from their LFS poiners to real `.csv` files.

How can one access raw `.csv` files that were once available in `assets/data/...` folders?

**Comment by sammacbeth** [comment]
Sorry, we ran over the LFS bandwidth this month. This should be fixed soon. In the meantime you can also get the data from the website. e.g. https://whotracks.me/data/2020-09/global/trackers.csv

**Comment by karlolukic** [comment]
> Sorry, we ran over the LFS bandwidth this month. This should be fixed soon. In the meantime you can also get the data from the website. e.g. https://whotracks.me/data/2020-09/global/trackers.csv

I see. Thanks for the quick response Sam and especially for the link.
