### ISSUE TITLE
"most tracked websites" tables are identical

### ISSUE THREAD

**Issue by sammacbeth** [cliqz-oss/whotracks.me#27]
On the home page, in the section "The most tracked websites", there is the option to display by "traffic" or "Average number of trackers". These two currently display exactly the same content (which is average number of trackers). 

We should show something different under "traffic", or not show it at all.

**Comment by ecnmst** [comment]
Fixed with https://github.com/cliqz-oss/whotracks.me/pull/29. Closing it.
