### ISSUE TITLE
Update WordPress Tracker Profile

### ISSUE THREAD

**Issue by michaeltieso** [cliqz-oss/whotracks.me#46]
https://whotracks.me/trackers/wordpress_stats.html#

WordPress Stats is used from [Jetpack](https://jetpack.com/).  Only changes I think that needs to be made is updating from Wordpress to WordPress and the link to jetpack.com.

**Comment by sammacbeth** [comment]
Hey, thanks for the report. I had a quick look into Jetpack - it seems it still operates entirely under the wp.com domain, which also seems to operate as a CDN for wordpress sites. We can split out the `pixel.wp.com` and `stats.wp.com` for Jetpack, and attribute the rest to Wordpress.

I'll also update the Wordpress link and set their parent company to [Automattic](https://automattic.com/).
