### ISSUE TITLE
Port default domain links to HTTPS

### ISSUE THREAD

**Issue by konark-cliqz** [cliqz-oss/whotracks.me#55]
Lot of the domains mentioned in trackers, we need to find a way to find the HTTPs equivalent.

<img width="611" alt="screen shot 2018-02-23 at 11 21 32" src="https://user-images.githubusercontent.com/10497229/36589504-caba090c-188b-11e8-9d11-76bb344137b8.png">

Eg:
https://whotracks.me/trackers/google_analytics.html
https://whotracks.me/trackers/bluekai.html

**Comment by ecnmst** [comment]
@konark-cliqz `upgrade_to_https` in `/whotracksme/qa/toodo.py` will now do a head request with the `https` alternative for `http` tracker urls, and create a task indicating the safe upgrades. Thanks for the issue
