### ISSUE TITLE
Data does not seem to be shipped with whotracksme from pypi

### ISSUE THREAD

**Issue by remusao** [cliqz-oss/whotracks.me#67]
There seems to be an issue with `whotracksme` when installed from pypi: the data is not packaged with the code. Also, would be nice to automatically update a new version on pypi every time the data is updated, this should be possible from travis.

**Comment by ecnmst** [comment]
You fixed it in https://github.com/cliqz-oss/whotracks.me/pull/85 :1st_place_medal:
